//! Minimal raw FFI bindings to libxmlsec1 (OpenSSL backend) + libxml2.
//!
//! This crate is a thin `-sys` layer: it exposes only the symbols the XML-DSig
//! sign/verify path uses (see `build.rs`'s allow-list). All unsafe orchestration
//! and the safe API live in `auth-service`'s `saml::crypto::xmlsec` module.
//!
//! Generated by bindgen at build time against the installed headers, so struct
//! layouts (notably `xmlSecDSigCtx`) track the linked library version rather
//! than being hand-transcribed.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
