services:
  playwright:
    build:
      dockerfile: docker/playwright.Dockerfile
    volumes:
      - ./tests:/app/tests
      - ./playwright-report:/app/playwright-report
      - ../frontend:/frontend:ro
    environment:
      PLAYWRIGHT_TEST_BASE_URL: http://application:3000
    depends_on:
      - application
    networks: [pw_network]
    
  application:
    image: debian:bookworm-slim
    working_dir: /app
    volumes:
      - ../target/release/eks:/app/eks:ro
    command: ["/app/eks"]
    environment:
      STORAGE_URL: memory://ephemeral
      BAG_SERVICE_URL: http://bag-service:8080
      TYPST_URL: http://typst-webservice:8080
      LOAD_FIXTURES: "true"
    depends_on:
      - bag-service
    networks: [pw_network]

  bag-service:
    image: ghcr.io/tweedegolf/bag-address-lookup:0.3.5
    networks: [pw_network]

  typst-webservice:
    image: ghcr.io/tweedegolf/typst-webservice:0.5.2
    volumes:
      - ../models:/templates:ro
    environment:
      TWS_DIR: /templates
    networks: [pw_network]

networks:
  pw_network:
    name: pw_network
