name: Deploy Rustdocs to GitHub Pages

permissions: {}
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches:
      - main


jobs:
  # Build Job
  build:
    name: Build pages
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Rust
        shell: bash
        run: >
          rustup update stable &&
          rustup default stable &&
          rustup component add rust-docs

      - name: Cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: eks

      - name: Build Documentation
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --workspace --no-deps --all-features

      - name: Add redirect to main crate docs
        run: echo '<meta http-equiv="refresh" content="0; url=eks/index.html">' > target/doc/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: './target/doc'

  deploy:
    name: Deploy pages
    environment:
      name: Rust crate documentation
      url: ${{ steps.deployment.outputs.page_url }}eks
    runs-on: ubuntu-24.04
    permissions:
      pages: write # to publish docs to the pages url of the repo
      id-token: write # to verify the source of the pages deployment
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
